# Generated by Django 5.0.9 on 2024-11-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_boot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='helmet',
            name='name',
            field=models.CharField(default='helmet', max_length=100),
        ),
        migrations.AlterField(
            model_name='boot',
            name='name',
            field=models.CharField(default='boot', max_length=100),
        ),
    ]
