# Generated by Django 5.0.9 on 2024-11-09 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_boot_image_glove_image_glove_name_helmet_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jacket',
            name='insulation_type',
        ),
    ]
