# Generated by Django 5.0.9 on 2024-11-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_order_item_id_remove_order_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
