# Generated by Django 5.0.9 on 2024-11-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boot',
            name='name',
            field=models.CharField(default='helmet', max_length=100),
        ),
    ]
