# Generated by Django 5.0.9 on 2024-11-10 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_jacket_insulation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glove',
            name='grip_type',
        ),
        migrations.RemoveField(
            model_name='pants',
            name='material',
        ),
    ]
