# Generated by Django 5.0.9 on 2024-11-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_glove_grip_type_remove_pants_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boot',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='glove',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='helmet',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jacket',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pants',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
