# Generated by Django 5.0.9 on 2024-11-16 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bookmarks_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
