--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bookmarks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bookmarks (
    id bigint NOT NULL,
    bookmarked_at timestamp(6) without time zone NOT NULL,
    image character varying(255),
    item_id bigint NOT NULL,
    item_type character varying(50) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.bookmarks OWNER TO postgres;

--
-- Name: bookmarks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bookmarks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookmarks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: boot; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.boot (
    id bigint NOT NULL,
    brand character varying(100) NOT NULL,
    color character varying(50) NOT NULL,
    image character varying(255),
    price integer NOT NULL,
    size character varying(50) NOT NULL,
    stock_quantity integer NOT NULL,
    waterproof boolean NOT NULL,
    image_link character varying(255)
);


ALTER TABLE public.boot OWNER TO postgres;

--
-- Name: boot_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.boot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.boot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: glove; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.glove (
    id bigint NOT NULL,
    brand character varying(255),
    color character varying(255),
    image_name character varying(255),
    name character varying(255),
    price integer NOT NULL,
    size character varying(255),
    stock_quantity integer NOT NULL,
    image_link character varying(255)
);


ALTER TABLE public.glove OWNER TO postgres;

--
-- Name: glove_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.glove ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.glove_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: helmets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.helmets (
    id bigint NOT NULL,
    brand character varying(100) NOT NULL,
    color character varying(50) NOT NULL,
    image_name character varying(255),
    name character varying(500),
    price integer NOT NULL,
    safety_rating character varying(50) NOT NULL,
    size character varying(50) NOT NULL,
    stock_quantity integer NOT NULL,
    image_link character varying(255) DEFAULT 'link'::character varying
);


ALTER TABLE public.helmets OWNER TO postgres;

--
-- Name: helmets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.helmets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.helmets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.items (
    id bigint NOT NULL,
    added_at date NOT NULL,
    helmet_id integer NOT NULL,
    image character varying(255),
    is_processed boolean NOT NULL,
    item_type character varying(50) NOT NULL,
    name character varying(40) NOT NULL,
    price integer NOT NULL,
    quantity integer NOT NULL,
    total_price numeric(38,2) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.items OWNER TO postgres;

--
-- Name: items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jacket; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jacket (
    id bigint NOT NULL,
    brand character varying(255),
    color character varying(255),
    image_name character varying(255),
    image_path character varying(255),
    image_type character varying(255),
    name character varying(255),
    price integer NOT NULL,
    size character varying(255),
    stock_quantity integer NOT NULL,
    image_link character varying(255)
);


ALTER TABLE public.jacket OWNER TO postgres;

--
-- Name: jacket_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.jacket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jacket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_items (
    order_id bigint NOT NULL,
    item_id bigint NOT NULL
);


ALTER TABLE public.order_items OWNER TO postgres;

--
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    is_processed boolean NOT NULL,
    order_number character varying(255) NOT NULL,
    ordered_at timestamp(6) without time zone NOT NULL,
    total_price numeric(10,2),
    user_id bigint NOT NULL
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pant; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pant (
    id bigint NOT NULL,
    brand character varying(100),
    color character varying(50),
    image_name character varying(255),
    image_path character varying(255),
    image_type character varying(255),
    name character varying(100),
    price integer,
    size character varying(50),
    stock_quantity integer,
    image_link character varying(255)
);


ALTER TABLE public.pant OWNER TO postgres;

--
-- Name: pant_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role character varying(255)
);


ALTER TABLE public.user_roles OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(100) NOT NULL,
    full_name character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: bookmarks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bookmarks (id, bookmarked_at, image, item_id, item_type, user_id) FROM stdin;
\.


--
-- Data for Name: boot; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.boot (id, brand, color, image, price, size, stock_quantity, waterproof, image_link) FROM stdin;
\.


--
-- Data for Name: glove; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.glove (id, brand, color, image_name, name, price, size, stock_quantity, image_link) FROM stdin;
4	MotoWolf	Black	1738133034978_img-2025-01-09-04-44-54-motowolf_carbon.png	Motowolf Carbon 349 Gloves	8200	S	31	\N
\.


--
-- Data for Name: helmets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.helmets (id, brand, color, image_name, name, price, safety_rating, size, stock_quantity, image_link) FROM stdin;
2	MT	Black	img-2024-11-06-01-34-38-thunder%20m%20black.png	MT Thunder 3 SV Solid	10500	4	M	5	https://res.cloudinary.com/dqtdcyoym/image/upload/v1740891825/img-2024-11-06-01-34-38-thunder_m_black_rfpqjt.webp
15	SHARK	White	img-2024-09-06-12-26-48-rhad%20white.png	Shark Skwal I3 Rhad	52000	5	L	0	https://res.cloudinary.com/dqtdcyoym/image/upload/v1740891824/img-2024-09-06-12-26-48-rhad_white_tqag4i.webp
14	SHARK	Black	img-2024-09-06-02-55-25-Molokai.png	Shark Ridill II Molokai	32000	4.5	L	2	https://res.cloudinary.com/dqtdcyoym/image/upload/v1740891824/img-2024-09-06-02-55-25-Molokai_s1mbzw.webp
16	Axxis	Green	img-2023-08-06-02-00-51-Scratch%205_3.png	Axxis Segment Scratch	6500	3	L	13	https://res.cloudinary.com/dqtdcyoym/image/upload/v1740891823/img-2023-08-06-02-00-51-Scratch_5_3_xpcemf.webp
19	AIROH	Green	img-2023-07-21-01-52-03-airoh-twist-2-0-lift-removebg-preview%20(1).png	Airoh Twist 2.0 Lift	48000	3.9	L	3	https://res.cloudinary.com/dqtdcyoym/image/upload/v1740891823/img-2023-08-06-02-00-51-Scratch_5_3_xpcemf.webp
13	IGNYTE Helmets	Black	ignyte.png	Ignyte IGN-4 Trever	8500	3.5	L	10	https://res.cloudinary.com/dqtdcyoym/image/upload/v1740891821/ignyte_tu4hhi.webp
18	AXOR Helmets	mix	img-2023-06-09-01-18-14-axorx.png	Axor X-Cross SC	12000	3.7	L	10	https://res.cloudinary.com/dqtdcyoym/image/upload/v1740891821/img-2023-06-09-01-18-14-axorx_jylxpl.webp
21	SteelBird	Black	img-2023-07-12-04-00-04-helmit-king-sb-34-zorro-vast-mat-.png	Steelbird SB-34 Vast	4000	3	L	20	https://res.cloudinary.com/dqtdcyoym/image/upload/v1740891822/img-2023-07-12-04-00-04-helmit-king-sb-34-zorro-vast-mat-_vrqb1u.webp
23	LS2	Red	img-2022-11-28-05-16-53-loop1.png	LS2 Stream Loop	8900	4	L	8	https://res.cloudinary.com/dqtdcyoym/image/upload/v1740891821/img-2022-11-28-05-16-53-loop1_yji8ve.webp
48	LS2	Black	img-2023-05-07-11-54-38-mono1.png	LS2 MX436 Pionner Solid	12250	4	L	12	https://res.cloudinary.com/dqtdcyoym/image/upload/v1740891821/img-2023-06-09-01-18-14-axorx_jylxpl.webp
52	Studds Helmets	Black	img-2023-07-12-03-39-01-51v-6-8s02L-removebg-preview.png	Studds Jet D5	2450	2	M	7	https://res.cloudinary.com/dqtdcyoym/image/upload/v1740891822/img-2023-07-12-03-39-01-51v-6-8s02L-removebg-preview_vbj3zb.webp
59	AXOR Helmets	Brown	img-2022-12-08-03-56-31-r2.png	Axor Jet Solid	6900	2	L	12	https://res.cloudinary.com/dqtdcyoym/image/upload/v1740891821/img-2022-12-08-03-56-31-r2_b8rxvm.webp
12	helmetKid	Blue	1738089140314_img-2022-12-11-04-50-22-blue1_(1).png	Vega Buds Full	2000	7	S	3	https://res.cloudinary.com/dqtdcyoym/image/upload/v1740989626/qbdefrsjbztirkjmi1nk.webp
\.


--
-- Data for Name: items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.items (id, added_at, helmet_id, image, is_processed, item_type, name, price, quantity, total_price, user_id) FROM stdin;
114	2025-03-03	13	ignyte.png	f	helmet	Ignyte IGN-4 Trever	8500	1	8500.00	18
115	2025-03-03	12	1738089140314_img-2022-12-11-04-50-22-blue1_(1).png	f	helmet	Vega Buds Full	2000	1	2000.00	18
113	2025-03-03	18	img-2023-06-09-01-18-14-axorx.png	f	helmet	Axor X-Cross SC	12000	2	24000.00	18
116	2025-03-03	3	img-2022-12-08-01-09-17-AXOR3.png	f	jacket	Axor Cruise 2	14425	2	28850.00	18
\.


--
-- Data for Name: jacket; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.jacket (id, brand, color, image_name, image_path, image_type, name, price, size, stock_quantity, image_link) FROM stdin;
2	KAVACH	Black	img-2023-12-10-01-06-25-kavach_winter_loqFlBD.png	/media/jackets/	png	Kavach Bomber Jacket	4500	M	2	https://res.cloudinary.com/dqtdcyoym/image/upload/v1740891906/img-2023-12-10-01-06-25-kavach_winter_nfmzq9.webp
3	AXOR	Black	img-2022-12-08-01-09-17-AXOR3.png	/media/jackets/	png	Axor Cruise 2	14425	L	1	https://res.cloudinary.com/dqtdcyoym/image/upload/v1740891905/img-2022-12-08-01-09-17-AXOR3_gxxhen.webp
4	Danmoshi	Green	img-2022-12-06-04-16-18-green1.png	/media/jackets/	png	Danmosi Riding Jacket	14500	L	2	https://res.cloudinary.com/dqtdcyoym/image/upload/v1740891904/img-2022-12-06-04-16-18-green1_p0te6d.webp
5	KAVACH	White	img-2023-09-29-02-59-00-hoodie_1.JPG.png	/media/jackets/	png	Kavach Zipper Hoodie	4500	M	3	https://res.cloudinary.com/dqtdcyoym/image/upload/v1740891905/img-2023-09-29-02-59-00-hoodie_1.JPG_s2onya.webp
\.


--
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_items (order_id, item_id) FROM stdin;
59	114
59	115
59	113
59	116
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (id, is_processed, order_number, ordered_at, total_price, user_id) FROM stdin;
59	f	ORD-6294525d-0e9e-4350-8b7b-35870d81ea1f	2025-03-03 11:52:45.486335	63350.00	18
\.


--
-- Data for Name: pant; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pant (id, brand, color, image_name, image_path, image_type, name, price, size, stock_quantity, image_link) FROM stdin;
1	KAVACH	Blue	img-2023-03-24-04-28-34-jeans.png	\N	\N	Kavach Riding Denim	8300	L	5	\N
3	KAVACH	Grey	img-2022-12-06-03-44-30-pant1.png	\N	\N	Kavach Pants	14500	L	4	\N
4	Motowolf	Black	img-2023-03-24-04-42-16-motowolf-pants.png	\N	\N	Motowolf Riding Pants	7000	M	2	\N
2	Motowolf	Blue	img-2024-11-08-11-40-06-mw%20combagt%20black.png	\N	\N	Motowolf Off-Track Pants	8500	L	3	\N
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_roles (user_id, role) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, full_name, password, role) FROM stdin;
1	user@example.com	John Doe	$2a$10$j6BVtmQPfC4jPaD8mVGLuO1OuCl6TxW75WCsTX9sULCB9d0eb0dHa	USER
6	user1@example.com	John Doe	$2a$10$Bj3lWxxWpSQzOtjWkIVDwOlKXmACTdPZ3.ouJY/K5kupvjdRF8B/e	USER
8	user2@example.com	John Doe	$2a$10$aqHGe2PmRXLzE1uObVCnbeENwUmBCwnHRZujhHVLvSj7G.Hj67tRW	USER
10	user3@example.com	John Doe	$2a$10$zfytpZQQbJOcqoEl/ohCQ.jFC6SJZQMrPFA9BDLjaEGTXoxAYKBOu	USER
11	user4@example.com	John Doe	$2a$10$WkB5Yx1niYPxYr1LW.edPuTaouOZ/0gdyk0jFni9t4Ie3zo6B6iN6	USER
12	user5@example.com	John Doe	$2a$10$gik5LHQmUO4Kwaf3kqvQ9O/tyuKrDnuAWTQdPzTR8y1TK3bhmsleG	USER
13	user6@example.com	John Doe	$2a$10$5rJkNuCJSoz7cAYD020bX.FPcch9PxGf49/xYUR7GLZJMssFAR3UO	USER
14	user7@example.com	John Doe	$2a$10$u7eYClsJEpjoDzrT9K1B.eIaWUj43iGSehFMbb3qY7OKInDRpmjL2	USER
15	user8@example.com	John Doe	$2a$10$oalrxJ6xMYk7r60ihSfnvubak71C5monjRy/VNEPKAuHw61eXjm6W	USER
16	user10@example.com	John Doe	$2a$10$Pq6Qpi9DPTzao.OjXP2BY..ascMQS9YYokuiEjCoquj3V6Jq91Ol.	USER
17	sudiphero@gmail.com	Sudip Hero	$2a$10$s7m6QQm.hkR15UZrXZGEl.oEh3CUXfM4GH7hVgqkrbqpfLrPtaQQS	USER
18	admin@email.com	admin	$2a$10$Z4wca30miOGVGOsWnyWLpOTv4sygLspt8Wss9wM2rm9U0fhFWmTUy	USER
19	sita@gmail.com	Sita	$2a$10$SGB4HZ4Hf02VtEMFlW8REezUNVO5fs7rI1Lvx5Jrqef4UZ6JQn8AS	USER
21	gita@email.com	gita	$2a$10$WMCmhmxnbFb1sApf8jeq.uA5Uldda1git0YHjTMd5toBC4uQod5sq	USER
22	tilak@email.com	tilak	$2a$10$zJbPUuNL6NM4Tbvkeghfh.d5rXfAhytbPeEgYRBPN38idTVYPNLv.	USER
23	radhika@email.com	radhika	$2a$10$NpZLYFdf31K.pGlZkYlhseOJbhB9RLla2OyhBbAJdRkJgidWkeMVG	USER
24	bikash@email.com	bikash	$2a$10$0zlmVjb3pVzJo3MfA1gIcu4D6NQUouQ04c6jl.4AswXYyWsXjoODG	USER
\.


--
-- Name: bookmarks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bookmarks_id_seq', 1, false);


--
-- Name: boot_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.boot_id_seq', 1, false);


--
-- Name: glove_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.glove_id_seq', 4, true);


--
-- Name: helmets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.helmets_id_seq', 12, true);


--
-- Name: items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.items_id_seq', 116, true);


--
-- Name: jacket_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.jacket_id_seq', 1, false);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_id_seq', 59, true);


--
-- Name: pant_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pant_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 24, true);


--
-- Name: bookmarks bookmarks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT bookmarks_pkey PRIMARY KEY (id);


--
-- Name: boot boot_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.boot
    ADD CONSTRAINT boot_pkey PRIMARY KEY (id);


--
-- Name: glove glove_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.glove
    ADD CONSTRAINT glove_pkey PRIMARY KEY (id);


--
-- Name: helmets helmets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.helmets
    ADD CONSTRAINT helmets_pkey PRIMARY KEY (id);


--
-- Name: items items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_pkey PRIMARY KEY (id);


--
-- Name: jacket jacket_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jacket
    ADD CONSTRAINT jacket_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: pant pant_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pant
    ADD CONSTRAINT pant_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: orders uknthkiu7pgmnqnu86i2jyoe2v7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT uknthkiu7pgmnqnu86i2jyoe2v7 UNIQUE (order_number);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: order_items ItemsOne; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT "ItemsOne" FOREIGN KEY (item_id) REFERENCES public.items(id) ON DELETE CASCADE NOT VALID;


--
-- Name: order_items OrdersOne; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT "OrdersOne" FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE NOT VALID;


--
-- Name: orders fk32ql8ubntj5uh44ph9659tiih; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: order_items fk88tn2oqcxl1034banqif9r70x; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fk88tn2oqcxl1034banqif9r70x FOREIGN KEY (item_id) REFERENCES public.items(id);


--
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: bookmarks fkdbsho2e05w5r13fkjqfjmge5f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT fkdbsho2e05w5r13fkjqfjmge5f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: items fkft8pmhndq1kntvyfaqcybhxvx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT fkft8pmhndq1kntvyfaqcybhxvx FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_roles fkhfh9dx7w3ubf1co1vdev94g3f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

