services:

  react-app:
      build: ./frontend
      ports:
        - "80:80"
      depends_on:
        - spring_app
      restart: always

  postgres_db:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ridesVault
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#      - ./ridesVaultBackupData.dump:/ridesVaultBackupData.dump


  spring_app:
    build: ./backendSpringBoot
    container_name: spring_app
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://caboose.proxy.rlwy.net:24514/railway
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: MMAplzgipqvxuJFaAPiugzupygeARoFJ

    restart: always

volumes:
  postgres_data:







